name: Update Release Notes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # GitHub's release notes generator uses these lables to select PRs to include
      - name: Label Pull Request by Changed Charts
        uses: maxisam/changed-files-labeler@0.1.1
        with:
            authToken: ${{ secrets.GITHUB_TOKEN }}
            basePaths: 'charts'
            prefixes: 'release-notes'
            delimiter: ':'
            layers: 1
